### ISSUE TITLE
Jetbrains Gateway has no response when starting codespaces

### ISSUE THREAD

**Issue by namhyuck-kim-otsk** [github/codespaces-jetbrains-feedback#101]
Hi, I am trying to open Github Codespaces with Jetbrains Webstorm IDE, but I get no response when I try to open it in Jetbrains Gateway. Please refer to the following for the error logs. It seems to be SSH problem but I couldn't find any solution to solve it. Any help would be appreciated.

## (Log) Webstorm
```
Codespace Display Name: legendary eureka
Codespace Machine: 4 cores, 8 GB RAM, 32 GB storage
Codespace Prebuild: false
Codespace Location: SouthEastAsia

2023-05-12 10:10:53,355 [  28042]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent - exited while
2023-05-12 10:10:53,355 [  28042]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent - Starting trigger poll for codespaces
2023-05-12 10:10:53,355 [  28042]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent - Finished trigger poll for codespaces
2023-05-12 10:10:53,402 [  28089]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Run async called, setting refreshing to false
2023-05-12 10:10:53,402 [  28089]   INFO - #com.github.codespaces.jetbrains.services.HttpClient - http client attempt 1 to send request jdk.internal.net.http.HttpRequestBuilderImpl@755391cd
2023-05-12 10:10:53,777 [  28464]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - refreshAvailableCodespaces was successful
2023-05-12 10:10:53,777 [  28464]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Recent view, filtering to only show recent codespaces
2023-05-12 10:10:53,777 [  28464]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - codespaces found while refreshing were different from existing codespaces
2023-05-12 10:10:53,777 [  28464]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Starting updating list in UI
2023-05-12 10:10:53,777 [  28464]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Finished updating list in UI
2023-05-12 10:10:53,777 [  28464]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Setting refreshing to false
2023-05-12 10:10:54,658 [  29345]   INFO - #com.github.codespaces.jetbrains.services.features.FlipperFeaturesService - Attempting to retrieve feature flags...
2023-05-12 10:10:54,658 [  29345]   INFO - #com.github.codespaces.jetbrains.services.HttpClient - http client attempt 1 to send request jdk.internal.net.http.HttpRequestBuilderImpl@209080cf
2023-05-12 10:10:58,416 [  33103]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Run async called, setting refreshing to false
2023-05-12 10:10:58,416 [  33103]   INFO - #com.github.codespaces.jetbrains.services.HttpClient - http client attempt 1 to send request jdk.internal.net.http.HttpRequestBuilderImpl@13955048
2023-05-12 10:10:58,755 [  33442]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - refreshAvailableCodespaces was successful
2023-05-12 10:10:58,755 [  33442]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Recent view, filtering to only show recent codespaces
2023-05-12 10:10:58,755 [  33442]   INFO - #com.github.codespaces.jetbrains.gateway.connector.env.CodespacesEnvComponent$ListCodespacesTask - Setting refreshing to false
2023-05-12 10:10:59,017 [  33704]   INFO - #com.github.codespaces.jetbrains.services.features.FlipperFeaturesService - Attempting to retrieve feature flags...
```

## (Log) Gateway

```
2023-05-12 10:10:18,441 [ 340487]   WARN - #c.j.g.s.SshMultistagePanelContext - SSH configuration ID  not found. Known configurations: Id: 0e6a320f-c604-438a-aefd-d5847d4d582a, name: apidev@localhost:62574, Id: 5a2d121f-85a4-4624-ad3c-0335fcf44d1f, name: apidev@localhost:62597, Id: 4714b931-152d-4800-8faa-d3f924c4dedc, name: apidev@localhost:63009, Id: 3f819c37-04d2-496e-b1fd-9050b72d3d28, name: apidev@localhost:63220, Id: 43bb6670-fe6e-40d1-9250-b6cb9733582b, name: apidev@localhost:63323, Id: f043c8fe-5f20-4960-90dc-bfa3941ac800, name: apidev@localhost:63422, Id: e0037a6b-fb85-4631-825e-c3543a68e2d2, name: apidev@localhost:63457, Id: bac6399f-f71c-4c39-9410-3bb6d69c457b, name: apidev@localhost:63476, Id: 14fbc6d5-2428-42ec-b87d-323b350141d0, name: apidev@localhost:63623, Id: 6bdd5899-7536-4396-994a-7f267421d49b, name: apidev@localhost:57943, Id: 02220451-fbf4-4db4-b179-4dd03ea5f1e2, name: apidev@localhost:58124, Id: 7c953aae-fa85-43ee-839a-bb2398fbd91a, name: apidev@localhost:58461
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - Exception in thread "ApplicationImpl pooled thread 3" java.lang.IllegalStateException: SSH configuration ID  not found.
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.SshMultistagePanelContext$Companion.guessBestSshConfigOrCreateNew(SshMultistagePanelContext.kt:77)
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.SshMultistagePanelContext$Companion.fromParameters(SshMultistagePanelContext.kt:84)
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.connection.SshGatewayConnectionProvider$connect$handle$1.invokeSuspend(SshGatewayConnectionProvider.kt:37)
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.connection.SshGatewayConnectionProvider$connect$handle$1.invoke(SshGatewayConnectionProvider.kt)
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.connection.SshGatewayConnectionProvider$connect$handle$1.invoke(SshGatewayConnectionProvider.kt)
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.deploy.DeployErrorProcessor$runDeployActionWithProgressAndErrorHandling$4.invokeSuspend(DeployErrorProcessor.kt:37)
2023-05-12 10:10:18,441 [ 340487]   INFO - STDERR - 	at com.jetbrains.gateway.ssh.deploy.DeployErrorProcessor$runDeployActionWithProgressAndErrorHandling$4.invoke(DeployErrorProcessor.kt)
```

**Comment by thomas-sickert** [comment]
Sorry you're running into issues @namhyuck-kim-otsk, could you please also include the Gateway + Codespaces plugin version?

Are you seeing this error every time you try to connect? 

I tried connecting to a Codespace with Webstorm on Gateway version: `GW-231.8770.69` and plugin version: `0.4.0.1213` and was able to connect. 

You can also check the `SSH Connection` window for the SSH configurations. It sounds like the one that's set up for the codespace is missing. You can view that by going to `SSH Connection` in the `All Providers` view and clicking `New Connection`.

![Screenshot 2023-05-11 at 10 36 03 PM](https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/bb667e12-6825-46e8-b375-08e2901ae644)

Then, click the cog next to the drop down and you'll be able to view all of the configurations. 

![Screenshot 2023-05-11 at 10 36 28 PM](https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/9ea9821c-1443-4d36-9872-b27eb6c5b93e)

You probably won't see one like: `apidev@localhost:63623` since the error message says you're missing it. If you could confirm that, it might also be helpful. The port for SSH is randomly generated on each connection, so it would be hard to add the missing configuration.

**Comment by namhyuck-kim-otsk** [comment]
Hi Thomas, thank you for the quick reply.

My current environment: Gateway (`GW-231.8770.69`), Codespace Plugin (`0.4.0.1148`)

When I click connect after selecting the IDE, I get a couple of loading dialog, but I get no response after that (no error message)

![image](https://github.com/github/codespaces-jetbrains-feedback/assets/125936281/78cd6ac0-8493-4e60-91d5-d96be2b90f30)

I checked the list of SSH configurations, but I get a bunch of keys.

Any idea why this is happening?

Thanks.
N.H Kim

**Comment by namhyuck-kim-otsk** [comment]
Many thanks for your effort.

I've tried running codespace via Jetbrains Gateway again, but still no response.

If you need more information, please feel free to let me know.

I hope to hear back from you soon!

**Comment by thomas-sickert** [comment]
No problem! 😄 

If you're able, I do have another could of things to try, and then an additional request:

### Install a Custom Version of the Gateway Plugin with a possible fix

1. Uninstall the Gateway Plugin in the JetBrains Gateway (you may be prompted to restart the gateway, go ahead and do that and then reopen this settings page)
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/55faa56a-45e8-4f98-923a-76a148360f44)

2. Install the attached version of the Gateway plugin by downloading it, and then loading the plugin from disk
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/c1677dd6-cb28-4ab9-9ca6-518bd02a2878)

3. Hit apply (restart the gateway if prompted) and then try to connect to the codespace again. If it doesn't work, try making a new codespace. If that doesn't work, then I'd like to get the `idea.log` from your Gateway so we can further investigate the error. 

### Getting the `idea.log`

On the Gateway landing page, there's a code in the bottom left. Please click that and then Collect All Logs:

![image](https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/d5830ae5-d69f-438f-a07e-9ce87933a5eb)

If you can attach the archive here, I can look more deeply into the logs and pass them along to JetBrains if it looks like we'll need their help solving the issue. 

Thanks in advance!

**Comment by namhyuck-kim-otsk** [comment]
Hi, I've attached the log archive below.

Please take a look and have a great day 👍🏻 

[gateway-logs-20230516-0946543344729430265762361.zip](https://github.com/github/codespaces-jetbrains-feedback/files/11482917/gateway-logs-20230516-0946543344729430265762361.zip)

**Comment by thomas-sickert** [comment]
Great, thanks for the logs. 

I've released a new version of the plugin that uses an updated SDK to manage the SSH configurations. If you could, please try updating the plugin and then restarting the gateway and trying again.

**Comment by namhyuck-kim-otsk** [comment]
Hi Thomas, thank you for your effort.
I've tried with the updated codespaces plugin, and I am met with the following error log:




**Description** 
Can not open Codepaces with Jetbrains Webstorm through Jetbrains Gateway.

**Steps to reproduce** 
Update Jetbrains Gateway & Codespaces Plugin to latest versions.
Follow the instruction and run codespaces.

**Impact** 
Met with following error log.

**Additional context** 
java.lang.NullPointerException: null cannot be cast to non-null type com.jetbrains.gateway.ssh.HostDeployInputs.FullySpecified
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1$run$1.invokeSuspend(CodespacesConnectorService.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1.run(CodespacesConnectorService.kt:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@143ca824, Dispatchers.Unconfined]
OS: Windows
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.6
Java Runtime Version: 17.0.6+10-b829.9
Java Vendor: JetBrains s.r.o.
Available CPUs: 8
Max Memory: 536870912
Free Memory: 65121000
Total Memory: 269484032
IDE Version: 2023.1.2
IDE: JetBrains Gateway 2023.1.2
Plugin Version: 0.4.0.1222
Plugin path: C:\Users\namhyuck.kim\AppData\Roaming\JetBrains\JetBrainsGateway2023.1\plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by Leezed525** [comment]
I also encountered the same situation,there are my information about my runtime envirment 
Plugin Github Codespaces version: 0.4.0.1222
Gh version: 2.29.0 (2023-05-10)
jetBrains gateway Version 2023 .1.2
          Build #GW-231.9011.34, built on May 16, 2023
          Runtime version: 17.0.6+10-b829.9 amd64

And the diffierence about me and [namhyuck-kim-otsk](https://github.com/namhyuck-kim-otsk) that is my chosen Ide is pychar m
I also chose the IDE IDEA,it also can't work out 

hope those information could help you to resolve this question.
thanks

**Comment by thomas-sickert** [comment]
Thanks for the stacktrace. It seems like the error has changed slightly, but this is still in the same callstack. I've reached out to JetBrains for some help on diagnosing this issue. 

@Leezed525 was this working for you previously? If it was, let me know and I can roll back the most recent version. If you'd like to manually roll back immediately, you can go to the [plugin page](https://plugins.jetbrains.com/plugin/20060-github-codespaces/versions?preview=true) and manually download and install the [previous version (0.4.0.1213)](https://plugins.jetbrains.com/plugin/20060-github-codespaces/versions/stable/332130) of the plugin.

**Comment by thomas-sickert** [comment]
Could you also make sure that you can connect to the codespace using the `gh cs ssh` command from the `gh` CLI?

**Comment by Leezed525** [comment]
it was my first time to try to use codespaces, the default ide for codespace is vs code.however I'd like to use ide from jetbrain so I try to use open in jetbrain gateway.


And i can sure that I can connect to the codespace.including open in browser or the command ```gh cs ssh ``` you tell me to do.There are my screen shots, the first one is open in browser ,and the second one is command ```gh cs ssh```
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/53244472/7923d494-c2b3-427d-8e65-851f5675f945)

![image](https://github.com/github/codespaces-jetbrains-feedback/assets/53244472/1cc23d6e-1915-4469-bdc4-f66f62686df8)

And i found another problem is that if i didn't open Jetbrain Gateway before I click the open in jetbrain gateway, it hasn't any response.  And i will never open the jetbrain gateway successfully even I just double click its icon in desktop until  I restart my computer 

Thanks a lot for you patient reading

**Comment by thomas-sickert** [comment]
Thank you for confirming that, could you provide the logs for the gateway using the [instructions here](https://github.com/github/codespaces-jetbrains-feedback/issues/101#issuecomment-1548275075)? 

I've narrowed down where the issue is happening but I'm not able to reproduce it myself.

**Comment by thomas-sickert** [comment]
I've removed the latest version of the plugin. If you uninstall and reinstall the plugin, you'll get the previous version. @namhyuck-kim-otsk this will probably result in the Configuration ID issue you were seeing before. @Leezed525, @squid233, @oiiakm, if you revert to the previous version, please let me know if you see any issues (especially if they're like the issue first reported in this thread)

**Comment by Leezed525** [comment]
I try to open in jetbrain gateway three time just now after I reinstall the plugin.Here is my idea.log file
And for your question 
+ [gateway-logs-20230523-2252531864875214448044666.zip](https://github.com/github/codespaces-jetbrains-feedback/files/11545515/gateway-logs-20230523-2252531864875214448044666.zip)
+ no,I never open in jetbrain gateway successfully with any codespaces (i had try two codespaces)
+ no
+ yes,I can ssh in my codespace,the result you can find in my last comment in this issue

thanks for you effort

**Comment by thomas-sickert** [comment]
Thank you for the additional logs, they're very helpful. 

I have a new build of the gateway plugin that might resolve the issues. You can [download](https://github.com/github/codespaces-jetbrains-feedback/releases/download/v0.4.0.1232-rc/github-codespaces-gateway-0.4.0.1232.zip) it and install it manually.

To do that:

1.  Open the gateway settings page and go to `Plugins` and uninstall the existing plugin:
<img width="894" alt="image" src="https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/102b249a-2f49-4841-9fbb-8a051fba0ade">

2. Click the cog and select `Install Plugin from Disk`. Find the `.zip` file that you downloaded from the link above and select the zip (no need to unzip it)
<img width="896" alt="image" src="https://github.com/github/codespaces-jetbrains-feedback/assets/80130182/4a6a818c-4f8c-4511-8ca3-fa0c08be5f6e">

3. Hit `Apply`, then `Ok` and then go back to the Gateway landing screen and go through the the same flow you have been.

**Comment by thomas-sickert** [comment]
The screenshots above show 0.4.0.1232 but the download links to 0.4.0.1233. I made some additional changes and pushed them around 30 minutes before posting this comment.

**Comment by namhyuck-kim-otsk** [comment]
> * If able, could you please provide the `idea.log` ([directions](https://github.com/github/codespaces-jetbrains-feedback/issues/101#issuecomment-1548275075)) from the gateway?
> * Was this working before?
> * Are you using a custom devcontainer?
> * If you haven't already, can you try ssh'ing into the codespace using `gh cs ssh` from the `gh` CLI tool?

I installed the plugin manually and sadly it doesn't work. Please refer to the following error log:

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@7463ff67, Dispatchers.Unconfined]

java.lang.NullPointerException: null cannot be cast to non-null type com.jetbrains.gateway.ssh.HostDeployInputs.FullySpecified
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1$run$1.invokeSuspend(CodespacesConnectorService.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1.run(CodespacesConnectorService.kt:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@7463ff67, Dispatchers.Unconfined]
```

To answer your questions:
- No. First time use
- No.
- It used to work but now I'm getting an error: `kex_exchange_identification: Connection closed by remote host`

**Comment by Leezed525** [comment]
I try to connect again after install plugin manually.But it also didn't work
And my error log is same like @namhyuck-kim-otsk

**Comment by thomas-sickert** [comment]
Just checking in to let you know that I'm still investigating the cause of this issue. No new developments yet, but I'll update back here when I have something new to report. Sorry for the inconvenience and thank you for your patience.

**Comment by Leezed525** [comment]
I 'm going to tell you a good information about this issue.
I change my personal computer and it connect to the codespace successfully.
The situtaiton about my previous computer is:
1.  the operating system is win 10
2.  the cpu is i5-8300H 
3.  the memory is 16g(8g * 2)

the situtation about current computer is :
1. the operating system is win 11(latest)
2. the cpu is i5-13600kf
3. the memory is 32g(32 * 1)

and there is my log from jetbrain Gateway which I successfully connect to the jetbrain gateway ,
[gateway-logs-20230604-23423713882512298190623521.zip](https://github.com/github/codespaces-jetbrains-feedback/files/11646011/gateway-logs-20230604-23423713882512298190623521.zip)

hope this information could help you resolve this problem and thanks for you effort

**Comment by albertopasqualetto** [comment]
Maybe the problem is linked to the absence of gh cli on the host.

**Comment by mikebronner** [comment]
Having this issue as well, reported in #108

**Comment by samwightt** [comment]
Also having this issue. This is making it very hard for me to adopt GitHub Codespaces at work as VSCode's Ruby tooling is not anywhere near RubyMine's.

I'm also experiencing it really intermittently. I've been able to get things to work about once.

**Comment by OscarGodson** [comment]
Yeah, I'm getting this issue too. I tried Idea and Webstorm. I did try ` gh cs ssh` and can access that fine. Everything is the latest as of today since i didn't have `gh` installed or Gateway. 

[gateway-logs-20231004-11143217504212096100542254.zip](https://github.com/github/codespaces-jetbrains-feedback/files/12806861/gateway-logs-20231004-11143217504212096100542254.zip)
