### ISSUE TITLE
Github Codespaces fails silently when clicking "connect" in the dialogue window

### ISSUE THREAD

**Issue by Madjid-CH** [github/codespaces-jetbrains-feedback#124]
**Description** 
when I click connect the "Preparing codespace" popup appear and then nothing happens
**Steps to reproduce** 
**Impact** 
**Additional context** 
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/100947451/35db2722-2403-4488-8ddc-c8f0c15bb4da)

com.jetbrains.gateway.ssh.deploy.DeployException: Worker binary deploy failed: check command log for details: File /root/.cache/JetBrains/RemoteDev/remote-dev-worker/remote-dev-worker_83eb3f8153ed29f38ae607b0a82d4ed8470bcd5f8f346034c4e370bb06d9dd64.13187761257800.tmp upload failed; stderr: 
	at com.jetbrains.gateway.ssh.GoWorkerDeployer.deploy$intellij_gateway_core(GoWorkerDeployer.kt:267)
	at com.jetbrains.gateway.ssh.GoWorkerDeployer$deploy$1.invokeSuspend(GoWorkerDeployer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService.getJetBrainsConnectionConfig(CodespacesConnectorService.kt:421)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService.getJetBrainsConnectionConfig$default(CodespacesConnectorService.kt:419)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$prepareForJetBrainsConnection$1.run(CodespacesConnectorService.kt:269)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: File /root/.cache/JetBrains/RemoteDev/remote-dev-worker/remote-dev-worker_83eb3f8153ed29f38ae607b0a82d4ed8470bcd5f8f346034c4e370bb06d9dd64.13187761257800.tmp upload failed; stderr: 
	at com.jetbrains.gateway.ssh.deploy.impl.SshUnixShellPipeFileAccessor.uploadFileFromLocalStream(SshUnixShellPipeFileAccessor.kt:52)
	at com.jetbrains.gateway.ssh.deploy.impl.SshUnixShellPipeFileAccessor$uploadFileFromLocalStream$1.invokeSuspend(SshUnixShellPipeFileAccessor.kt)
	... 34 more
Caused by: java.lang.IllegalStateException: File upload failed with exit code null
	at com.jetbrains.gateway.ssh.deploy.impl.SshUnixShellPipeFileAccessor.uploadFileFromLocalStream(SshUnixShellPipeFileAccessor.kt:48)
	... 35 more
OS: Windows
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.8
Java Runtime Version: 17.0.8+7-b1000.8
Java Vendor: JetBrains s.r.o.
Available CPUs: 8
Max Memory: 2147483648
Free Memory: 110045024
Total Memory: 327155712
IDE Version: 2023.2.1
IDE: PyCharm 2023.2.1
Plugin Version: 0.5.0.1214
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by Madjid-CH** [comment]
here's the idea.log file
[idea.log](https://github.com/github/codespaces-jetbrains-feedback/files/12542220/idea.log)

**Comment by luq7** [comment]
Similar issue, I have seen other proposed [solution](https://github.com/orgs/community/discussions/68150). But I wonder what the official folks say.

**Comment by luq7** [comment]
@Madjid-CH  did you do [this step](https://docs.github.com/en/codespaces/developing-in-a-codespace/using-github-codespaces-in-your-jetbrains-ide#codespace-running-an-ssh-server) in your Codespace? Apparently that solved the long wait and failed to connect.

**Comment by Madjid-CH** [comment]
> @Madjid-CH did you do [this step](https://docs.github.com/en/codespaces/developing-in-a-codespace/using-github-codespaces-in-your-jetbrains-ide#codespace-running-an-ssh-server) in your Codespace? Apparently that solved the long wait and failed to connect.

Yes I did that @luq7
