### ISSUE TITLE
Recovery Container Status Check Failed

### ISSUE THREAD

**Issue by ihor-sviziev** [github/codespaces-jetbrains-feedback#16]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
```
java.lang.Throwable: Could not get recovery container status: com.microsoft.tunnels.connections.TunnelConnectionException: Error verifying the ssh session.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.github.codespaces.jetbrains.observability.logging.GitHubLogger.error(GitHubLogger.kt:31)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1.run(CodespacesConnectorService.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS Version: 13.0.1
OS Architecture: aarch64
IDE Version: 2022.2.4
Plugin Version: 0.2.0.896
Plugin path: /Users/ihor/Library/Application Support/JetBrains/Toolbox/apps/Gateway/ch-0/222.4459.11/JetBrains Gateway.app.plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by shayneburgess** [comment]
We are working on a fix for this and will get an update out as soon as we have it

**Comment by cmuto09** [comment]
This issue is resolved in the latest version of the plugin. You can update your Gateway plugin by following [these steps](https://github.com/github/codespaces-jetbrains-feedback/issues/46#issuecomment-1331394327), and that should fix the issue you're seeing

**Comment by cmuto09** [comment]
Closing this issue as resolved

**Comment by mhrohani1385** [comment]
Thanks
