### ISSUE TITLE
NumberFormatException: For input string: "0+dfsg1" in JetBrains Gateway

### ISSUE THREAD

**Issue by ideadapt** [github/codespaces-jetbrains-feedback#17]
```
~$ gh --version
gh version 2.4.0+dfsg1 (2022-03-23 Ubuntu 2.4.0+dfsg1-2)
https://github.com/cli/cli/releases/latest
```

Stacktrace:
```
java.lang.NumberFormatException: For input string: "0+dfsg1"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhVersion$Companion.fromString(GhVersion.kt:31)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClient.isValidVersion(GhClient.kt:194)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClient.isNotValidVersion(GhClient.kt:190)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClient.validate(GhClient.kt:154)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClients(GhClientService.kt:77)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClient(GhClientService.kt:69)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.getClient(GhClientService.kt:41)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$1.run(CodespacesConnectorService.kt:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

GitHub Codespaces plugin version: 0.2.0.896

**Comment by shayneburgess** [comment]
We will work on a fix for this and publish it

**Comment by cmuto09** [comment]
Hey @ideadapt- this is resolved in our latest version of the plugin. You can update by following the [instructions here](https://github.com/github/codespaces-jetbrains-feedback#updating-the-codespaces-plugin)
