### ISSUE TITLE
GitHub Codespaces Feedback

### ISSUE THREAD

**Issue by TheCloutEngineer** [github/codespaces-jetbrains-feedback#30]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
```
java.lang.Throwable: error getting ssh server details: failed to start server: 
Please check if an SSH server is installed in the container.
If the docker image being used for the codespace does not have an SSH server,
install it in your Dockerfile or, for codespaces that use Debian-based images,
you can add the following to your devcontainer.json:

"features": {
    "ghcr.io/devcontainers/features/sshd:1": {
        "version": "latest"
    }
}


	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.github.codespaces.jetbrains.observability.logging.GitHubLogger.error(GitHubLogger.kt:31)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$prepareForJetBrainsConnection$1.run(CodespacesConnectorService.kt:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS Version: 13.0.1
OS Architecture: x86_64
IDE Version: 2022.2.4
Plugin Version: 0.2.0.896
Plugin path: /Users/khalilsaboor/Library/Application Support/JetBrains/Toolbox/apps/Gateway/ch-0/222.4459.11/JetBrains Gateway.app.plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment]
Hi @TheCloutEngineer!

In order to connect to your codespace via the JetBrains Gateway you need to ensure your codespace has an SSH server installed. The easiest way to do that is to add the [SSH feature](https://github.com/devcontainers/features/tree/main/src/sshd) to your `devcontainer.json` definition, like this:

```jsonc
{
    // ...existingDevcontainer,
    "features": {
        // ...existingFeatures,
        "ghcr.io/devcontainers/features/sshd:1": {
            "version": "latest"
        }
    }
}
```

After making that change you should [rebuild your codespace](https://cli.github.com/manual/gh_codespace_rebuild) to apply the update.

Let me know if that helps!

**Comment by TheCloutEngineer** [comment]
thanks this helps
