### ISSUE TITLE
is that  error known?

### ISSUE THREAD

**Issue by dominicusin** [github/codespaces-jetbrains-feedback#32]
java.lang.Throwable: ID 'GitHub.Codespaces.Feedback' is already taken by action 'Codespaces: Send Feedback to GitHub (Send feedback to GitHub. Note: this will create a public issue in a GitHub repository.)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction) . Action 'Codespaces: Send Feedback to GitHub (Send feedback to GitHub. Note: this will create a public issue in a GitHub repository.)' (class com.github.codespaces.jetbrains.common.platform.action.FeedbackAction) cannot use the same ID null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1326)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1263)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1335)
	at com.github.codespaces.jetbrains.common.platform.action.FeedbackAction$Companion.register(FeedbackAction.kt:22)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnector.initProcedure(CodespacesConnector.kt:45)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeScreenPanel.<init>(GatewayWelcomeScreenPanel.kt:38)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeTabFactory$GatewayTab.buildComponent(GatewayWelcomeTabFactory.kt:71)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$DefaultWelcomeScreenTab.getAssociatedComponent(TabbedWelcomeScreen.java:207)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$1.create(TabbedWelcomeScreen.java:167)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$1.create(TabbedWelcomeScreen.java:158)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:73)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:101)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:86)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.lambda$new$0(TabbedWelcomeScreen.java:45)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeScreenLeftPanel.addSelectionListener$lambda-1(GatewayWelcomeScreenCustomization.kt:74)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(JList.java:1831)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1845)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeScreenLeftPanel.init(GatewayWelcomeScreenCustomization.kt:100)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.loadTabs(TabbedWelcomeScreen.java:114)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.loadTabs(TabbedWelcomeScreen.java:98)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeFrame$1.invoke(GatewayWelcomeFrame.kt:18)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeFrame$1.invoke(GatewayWelcomeFrame.kt:17)
	at com.jetbrains.gateway.api.GatewayConnector$Companion$onConnectorsChange$1.extensionAdded(GatewayConnector.kt:56)
	at com.jetbrains.gateway.api.GatewayConnector$Companion$onConnectorsChange$1.extensionAdded(GatewayConnector.kt:55)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:753)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:957)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin$lambda-29(DynamicPlugins.kt:860)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:955)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:843)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:817)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:410)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:388)
	at com.intellij.ide.plugins.PluginManagerMain$1.lambda$run$0(PluginManagerMain.java:115)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
OS: Windows Server 2022
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.14
Java Vendor: JetBrains s.r.o.
Available CPUs: 20
Max Memory: 536870912
Free Memory: 43255552
Total Memory: 150994944
IDE Version: 2022.3 RC
IDE: JetBrains Gateway 2022.3 RC
Plugin Version: 0.3.0.931
Plugin path: D:\IDE\JetBrains\Toolbox\apps\Gateway\ch-0\223.7571.70.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment]
Thanks for the report @dominicusin. This has been added to our backlog- will let you know when there is an update!
