### ISSUE TITLE
GitHub Codespaces Feedback

### ISSUE THREAD

**Issue by ENate** [github/codespaces-jetbrains-feedback#33]
- I installed the Gateway and Codespaces plugin as described. tried connecting to Codespaces via the Jetbrains plugin and got the following error/trace:
```
Cannot select using PAC

java.lang.NoClassDefFoundError: org/ini4j/Ini
	at com.github.markusbernhardt.proxy.search.browser.firefox.FirefoxSettingParser.getSettingsFile(FirefoxSettingParser.java:101)
	at com.github.markusbernhardt.proxy.search.browser.firefox.FirefoxSettingParser.parseSettings(FirefoxSettingParser.java:47)
	at com.github.markusbernhardt.proxy.search.browser.firefox.FirefoxProxySearchStrategy.readSettings(FirefoxProxySearchStrategy.java:171)
	at com.github.markusbernhardt.proxy.search.browser.firefox.FirefoxProxySearchStrategy.getProxySelector(FirefoxProxySearchStrategy.java:106)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:220)
	at com.intellij.util.io.IoServiceImpl.getProxySelector(IoServiceImpl.java:19)
	at com.intellij.util.net.NetUtils.getProxySelector(NetUtils.java:220)
	at com.intellij.util.net.IdeaWideProxySelector.selectUsingPac(IdeaWideProxySelector.java:86)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:62)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:215)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at com.github.codespaces.jetbrains.gateway.connector.ide.IdeService.getIdes(IdeService.kt:32)
	at com.github.codespaces.jetbrains.gateway.connector.ide.IdeService.getIdes$default(IdeService.kt:21)
	at com.github.codespaces.jetbrains.gateway.tasks.ListIdesTask.run(ListIdesTask.kt:12)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.ini4j.Ini
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
......
```

**Comment by cmuto09** [comment]
Hey @ENate- based on the error it looks like there's a proxy active that may be keeping you from connecting. Is it possible to try to connect without the proxy active?
