### ISSUE TITLE
GitHub Codespaces Feedback

### ISSUE THREAD

**Issue by scottdensmore** [github/codespaces-jetbrains-feedback#46]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
```
java.lang.Throwable: Could not get recovery container status: UNAVAILABLE: io exception
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.github.codespaces.jetbrains.observability.logging.GitHubLogger.error(GitHubLogger.kt:31)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$connect$1.run(CodespacesConnectorService.kt:104)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS Version: 13.0.1
OS Architecture: x86_64
IDE Version: 2022.2.4
Plugin Version: 0.2.0.896
Plugin path: /Users/scottdensmore/Library/Application Support/JetBrains/Toolbox/apps/Gateway/ch-0/222.4459.11/JetBrains Gateway.app.plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment]
Hi @scottdensmore- this issue is resolved in the latest available plugin on the JetBrains marketplace. If you update your Codespaces plugin this issue should go away:

1. Open the Gateway
2. Go to `Preferences > Plugins`
3. Go to the `Installed` tab
4. Apply the update, and restart the Gateway if needed

![Screenshot 2022-11-29 at 15 17 35](https://user-images.githubusercontent.com/4679612/204660790-af17ff4f-3daf-4409-970f-3d44fc8e9f59.png)
![Screenshot 2022-11-29 at 15 17 56](https://user-images.githubusercontent.com/4679612/204660804-4d47dc30-ffdd-4c4a-ae64-f9587f9a1ba1.png)

**Comment by scottdensmore** [comment]
Works great now! Thanks!
