### ISSUE TITLE
Codespace not found

### ISSUE THREAD

**Issue by saikartheekb** [github/codespaces-jetbrains-feedback#50]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
java.lang.Exception: Codespace not found
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$prepareForJetBrainsConnection$1.run(CodespacesConnectorService.kt:184)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:509)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS: Windows 10
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.14
Java Vendor: JetBrains s.r.o.
Available CPUs: 4
Max Memory: 536870912
Free Memory: 152681960
Total Memory: 227540992
IDE Version: 2022.3
IDE: JetBrains Gateway 2022.3
Plugin Version: 0.3.0.951
Plugin path: D:\Softwares\apps\Gateway\ch-0\223.7571.203.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by thomas-sickert** [comment]
Hey @saikartheekb, thanks for the report. Just a few follow up questions:

If you have the codespace name, could you provide that? 

Were you able to connect after retrying?

What are the repro steps? Was this a new codespace that you had just created on GitHub or were you trying to connect to an old codespace?

What is your retention period is set to?

**Comment by saikartheekb** [comment]
Hi @thomas-sickert 
All of these issues are  with new codespaces I just created. I deleted the codepsaces and created them again.
For all other errors, IDE automatically submitted tickets except for this one, it redirected me here to submit the stack trace.
I eventually could successfully connected to the codespaces after several retries.
I faced these errors when I tried to change the machine type from 2 cores to 8/16 cores machine. The transition from 2 cores to 4 cores was smooth.
The retention period is set to 30 days.
