### ISSUE TITLE
Sometimes I can't connect to a project because the host status commands are timing out

### ISSUE THREAD

**Issue by AnnaPrints** [github/codespaces-jetbrains-feedback#55]
Build #GW-223.8214.4, built on December 6, 2022

Steps:

1. I created a dev environment from my own repository
2. Selected IDEA 2022.3 to join

Result: Very often I cannot connect, because deploy failed. Retry usually doesn't help

Interesting from logs:
`2022-12-07 10:46:59,952 [  12670]   INFO - #c.j.r.u.RemoteDevModalDialogOnProjectOpenInterceptor - Not going to intercept dialog "" (com.intellij.openapi.progress.util.ProgressDialog$MyDialogWrapper)`

`2022-12-07 11:47:33,372 [1014841]   INFO - #c.j.g.s.d.DeployErrorProcessor - Deploy failed with exception, will show deploy failure UI
com.jetbrains.gateway.ssh.deploy.DeployException: Host process terminated unexpectedly with unknown error. See logs for more details
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:172)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:168)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:158)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:507)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: Host process terminated unexpectedly with unknown error. See logs for more details
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:192)
	... 35 more
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: Host process terminated unexpectedly with unknown error. See logs for more details
	at com.jetbrains.gateway.ssh.deploy.methods.HostRunMethods.openProject(HostRunMethods.kt:208)
	at com.jetbrains.gateway.ssh.deploy.methods.HostRunMethods.access$openProject(HostRunMethods.kt:30)
	at com.jetbrains.gateway.ssh.deploy.methods.HostRunMethods$openProject$1.invokeSuspend(HostRunMethods.kt)
	... 35 more`
[gateway-logs-20221207-11473611986069821604166555.zip](https://github.com/github/codespaces-jetbrains-feedback/files/10175471/gateway-logs-20221207-11473611986069821604166555.zip)

**Comment by thomas-sickert** [comment]
Hey @AnnaPrints, sorry you're running into issues. Are you trying to connect to a 2 core machine? This looks like an error we see often with smaller codespaces that run out of resources to run the JetBrains IDEs. If you are, bumping up the size to 4 cores or more should help
