### ISSUE TITLE
Connecion to Github Coedspaces fails

### ISSUE THREAD

**Issue by motabass** [github/codespaces-jetbrains-feedback#58]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
com.jetbrains.gateway.ssh.deploy.DeployException: Worker binary deploy failed: check command log for details: Process for command /bin/bash -lc echo\ REMOTE_EXEC_OUTPUT_MARKER_\ \&\&\ test\ -f\ /home/codespace/.cache/JetBrains/RemoteDev/remote-dev-worker/remote-dev-worker_ba9509c11d96c6ce33a39e248d584be92d7de751a8acb9b7e9872b6136aa4876 didn't exit in time
	at com.jetbrains.gateway.ssh.GoWorkerDeployer.deploy$intellij_gateway_core(GoWorkerDeployer.kt:238)
	at com.jetbrains.gateway.ssh.GoWorkerDeployer$deploy$1.invokeSuspend(GoWorkerDeployer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService.getJetBrainsConnectionConfig(CodespacesConnectorService.kt:294)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService.getJetBrainsConnectionConfig$default(CodespacesConnectorService.kt:292)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$prepareForJetBrainsConnection$1.run(CodespacesConnectorService.kt:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:509)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Process for command /bin/bash -lc echo\ REMOTE_EXEC_OUTPUT_MARKER_\ \&\&\ test\ -f\ /home/codespace/.cache/JetBrains/RemoteDev/remote-dev-worker/remote-dev-worker_ba9509c11d96c6ce33a39e248d584be92d7de751a8acb9b7e9872b6136aa4876 didn't exit in time
	at com.jetbrains.gateway.ssh.deploy.ShellFacade.executeAndReturnExitCode(ShellFacade.kt:193)
	at com.jetbrains.gateway.ssh.deploy.ShellFacade$executeAndReturnExitCode$1.invokeSuspend(ShellFacade.kt)
	... 32 more
OS: Windows 11
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.14
Java Vendor: JetBrains s.r.o.
Available CPUs: 8
Max Memory: 536870912
Free Memory: 79381928
Total Memory: 213909504
IDE Version: 2022.3
IDE: JetBrains Gateway 2022.3
Plugin Version: 0.3.0.971
Plugin path: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\Gateway\ch-0\223.7571.203.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by motabass** [comment]
Hi. I tried with a 4 core machine with a free codespaces subscription. 8 core machines are not available for me to test sadly.
