### ISSUE TITLE
error occured wile trying to connect to remote server

### ISSUE THREAD

**Issue by mehediois** [github/codespaces-jetbrains-feedback#65]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
java.lang.ClassCastException: kotlin.collections.EmptyList cannot be cast to kotlin.collections.MutableList
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.runResolvers(GhClientService.kt:88)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClients(GhClientService.kt:76)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClient(GhClientService.kt:72)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.getClient(GhClientService.kt:44)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$1.run(CodespacesConnectorService.kt:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS: Windows 10
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.23
Java Vendor: JetBrains s.r.o.
Available CPUs: 8
Max Memory: 786432000
Free Memory: 281271896
Total Memory: 786432000
IDE Version: 2022.3.1
IDE: PhpStorm 2022.3.1
Plugin Version: 0.3.0.971
Plugin path: C:\Users\MehediSC\AppData\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\223.8214.64.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by AyeshaGagguturi** [comment]
Thanks for bring this up @mehediois! - We are tracking and working on this item.
