### ISSUE TITLE
Unable to use Codespaces from PyCharm

### ISSUE THREAD

**Issue by gelliott-fincad** [github/codespaces-jetbrains-feedback#68]
**Description** 
Despite gh client being able to identify a codespace created in GitHub the plug in could not find the codespace. There is no indication why this is the case.

(.venv) gordon@eu-ws-ge0:~/project/blackbird$ gh codespace list
NAME                                              REPOSITORY           BRANCH                         STATE      CREATED AT
gelliott-fincad-congenial-eureka-pqr74********  financialcad/falcon  ge--mdw-3334_*******  Available  29m

**Steps to reproduce** 
In PyCharm, open Remote Development...
Click on Connect to Codespaces
Blank page with just "Connect" and "Back" buttons is shown.
Clicking Connect produces this error

**Impact** 
Unable to use Codespaces

**Additional context** 
java.lang.Exception: Codespace not found
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$prepareForJetBrainsConnection$1.run(CodespacesConnectorService.kt:193)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:507)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS: Linux
OS Version: 5.15.0-56-generic
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.23
Java Vendor: JetBrains s.r.o.
Available CPUs: 16
Max Memory: 2147483648
Free Memory: 296894240
Total Memory: 893386752
IDE Version: 2022.3.1
IDE: PyCharm 2022.3.1
Plugin Version: 0.3.0.971
Plugin path: /home/gordon/.local/share/JetBrains/PyCharm2022.3/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment]
Hi @gelliott-fincad! Thanks for your report. Are you attempting to connect through the JetBrains Gateway application, or a locally installed version of PyCharm? Connecting through the Gateway is the primary supported path right now, and we have seen reports of flakiness when trying to connect through the PyCharm IDE directly

**Comment by gelliott-fincad** [comment]
Hi @cmuto09, I'm using the File, Remote Development.. option from a locally installed version of PyCharm. Please see the steps to reproduce above.

**Comment by cmuto09** [comment]
Ah, thanks for the clarification. Yeah there are some known issues with connecting to remote development through the actual downloaded IDEs. We are working on investigating and addressing them, but in the meantime you should be able to connect successfully through the [JetBrains Gateway](https://photos5.appleinsider.com/gallery/29519-47664-Facebook-research-l.jpg) rather than through PyCharm directly
