### ISSUE TITLE
GitHub Codespaces Feedback

### ISSUE THREAD

**Issue by octosteve** [github/codespaces-jetbrains-feedback#7]
**Description** 
Codespaces not opening
**Steps to reproduce** 
Tried to connect in Current EAP
**Impact** 
Can't use codespaces plugin
**Additional context** 
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.base/java.util.Collections$SingletonList.get(Collections.java:4959)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhVersion$Companion.fromString(GhVersion.kt:24)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClient.isValidVersion(GhClient.kt:194)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClient.isNotValidVersion(GhClient.kt:190)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClient.validate(GhClient.kt:154)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClients(GhClientService.kt:77)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClient(GhClientService.kt:69)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.getClient(GhClientService.kt:41)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$1.run(CodespacesConnectorService.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS Version: 12.6
OS Architecture: x86_64
IDE Version: 2022.3 Beta
Plugin Version: 0.3.0.898
Plugin path: /Users/octosteve/Library/Application Support/JetBrains/RubyMine2022.3/plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by octosteve** [comment]
Fixed this by uninstalling `gh` and reinstalling. I was on `head` via `brew`
