### ISSUE TITLE
Pycharm Error while trying to connect to codespace "gh CLI is not set up properly". Problems with Pycharm and Gateway.

### ISSUE THREAD

**Issue by PlusPlusMan** [github/codespaces-jetbrains-feedback#74]
**Description** 
I was trying to connect to codespace via Pycharm Professional. When I enter remote development menu and choose codespace, what I get is totally blank window, with only connect button. After I press this I get this error and notification 'gh CLI is not set up properly' I tried to configure it by attaching path to gt.exe file, didn't work. Then i created ssh for my codespace and included it as path in Pycharm and it also didn't work. I tried to connect to codespace via Gateway, but, I have few problems with that. When I choose my codespace and my IDE - Pycharm, then sometimes nothing happen, but sometimes it opens the codespace server, but not in pycharm but in gateway editor, also, I have no idea why Gateway pushes my cpu to 90% usage alone and totally freezes my pc, while Pycharm at highs goes to few max, somethings wrong. 

**Steps to reproduce** 
**Impact** 
**Additional context** 
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\gh.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.resolver.FileResolver.<init>(FileResolver.kt:18)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.resolver.FileResolver.<init>(FileResolver.kt:18)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.getClient(GhClientService.kt:44)
	at com.github.codespaces.jetbrains.gateway.settings.CodespacesSettingsConfigurable$apply$2.run(CodespacesSettingsConfigurable.kt:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS: Windows 11
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.23
Java Vendor: JetBrains s.r.o.
Available CPUs: 8
Max Memory: 2136997888
Free Memory: 657356392
Total Memory: 1045430272
IDE Version: 2022.3.1
IDE: PyCharm 2022.3.1
Plugin Version: 0.3.0.971
Plugin path: C:\Users\rkeyu\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\223.8214.51.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment]
Hmm... I haven't come across this issue. Thank you for the reports @PlusPlusMan and @vremyavnikuda- we will investigate further on our side.

Do you mind sharing [your idea.log](https://docs.github.com/en/codespaces/troubleshooting/github-codespaces-logs?tool=jetbrains#jetbrains-logs) as well so we can get a better picture of what is happening?
