### ISSUE TITLE
Codespaces Plugin for Clion latest version crashes on start

### ISSUE THREAD

**Issue by codehampster** [github/codespaces-jetbrains-feedback#75]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
java.lang.ClassCastException: kotlin.collections.EmptyList cannot be cast to kotlin.collections.MutableList
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.runResolvers(GhClientService.kt:88)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClients(GhClientService.kt:76)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.findClient(GhClientService.kt:72)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.getClient(GhClientService.kt:44)
	at com.github.codespaces.jetbrains.services.connection.liveshare.client.GhClientService.getClient$default(GhClientService.kt:37)
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorComponent.<init>(CodespacesConnectorComponent.kt:62)
	at com.github.codespaces.jetbrains.gateway.connector.recentConnections.CodespaceWorkspacesView.<init>(CodespaceWorkspacesView.kt:7)
	at com.github.codespaces.jetbrains.gateway.connector.recentConnections.CodespaceRecentConnections.createRecentsView(CodespaceRecentConnections.kt:23)
	at com.jetbrains.gateway.welcomeScreen.GatewayWelcomeTabFactory$GatewayRecentsTab.buildComponent(GatewayWelcomeTabFactory.kt:112)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$DefaultWelcomeScreenTab.getAssociatedComponent(TabbedWelcomeScreen.java:207)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$1.create(TabbedWelcomeScreen.java:167)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$1.create(TabbedWelcomeScreen.java:158)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:73)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:101)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:86)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.lambda$new$0(TabbedWelcomeScreen.java:45)
	at com.intellij.openapi.wm.impl.welcomeScreen.TreeWelcomeScreenLeftPanel.addSelectionListener$lambda$1(TreeWelcomeScreenLeftPanel.kt:74)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:3020)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3521)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:650)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:649)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1120)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:306)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:200)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1709)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2764)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4099)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:4038)
	at com.intellij.util.ui.MouseEventAdapter.mousePressed(MouseEventAdapter.java:31)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6645)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:424)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
OS: Mac OS X
OS Version: 13.2
OS Architecture: aarch64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.23
Java Vendor: JetBrains s.r.o.
Available CPUs: 10
Max Memory: 4294967296
Free Memory: 1693086496
Total Memory: 3313500160
IDE Version: 2022.3.1
IDE: CLion 2022.3.1
Plugin Version: 0.3.0.971
Plugin path: /Users/petertomich/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8214.51/CLion.app.plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by cmuto09** [comment]
Thanks for the report @codehampster! We have heard reports of issues when connecting via the IDEs directly rather than using the JetBrains Gateway. Do you mind installing [the Gateway](https://github.com/github/codespaces-jetbrains-feedback#install-compatible-jetbrains-gateway) and attempting to connect through that application?

**Comment by codehampster** [comment]
I had gateway already but this issue has been resolved in the later versions. please close
