### ISSUE TITLE
tried to connect to new github codespace

### ISSUE THREAD

**Issue by Newtopian** [github/codespaces-jetbrains-feedback#86]
**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
java.lang.Exception: gh CLI is not set up properly
	at com.github.codespaces.jetbrains.gateway.connector.CodespacesConnectorService$prepareForJetBrainsConnection$1.run(CodespacesConnectorService.kt:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
OS: Windows 10
OS Version: 10.0
OS Architecture: amd64
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.25
Java Vendor: JetBrains s.r.o.
Available CPUs: 12
Max Memory: 536870912
Free Memory: 126407008
Total Memory: 231735296
IDE Version: 2022.3.2
IDE: JetBrains Gateway 2022.3.2
Plugin Version: 0.3.0.1106
Plugin path: C:\tools\JetBrains\apps\Gateway\ch-0\223.8617.56.plugins\github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by AyeshaGagguturi** [comment]
Do you have the lates gh cli installed on your local machine?

**Comment by Sarvesh-Kesharwani** [comment]
> 

I do have, without that i couldn't install github codespace plugin into jetbrains getway.
please look into it, i really need the access to codespace from pycharm asap.

**Comment by thomas-sickert** [comment]
@Sarvesh-Kesharwani The `gh` CLI is no longer a requirement in the newest version of the Codespaces plugin. If you update to 231+ and install the corresponding gateway plugin, you should clear this message.

**Comment by kms0219kms** [comment]
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/67222970/4ed9de54-3668-48d9-bf32-aea1437c7737)
I have same issue. I've installed Gateway today, so I am sure it is latest version but they needs GH CLI. so I've installed GH CLI and logined but I've got gh CLI is not set up properly error.

**Comment by kms0219kms** [comment]
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/67222970/ae8de4a8-78c9-4580-82e3-01df2b5db398)

**Comment by kms0219kms** [comment]
I've solved this issue. Can you try to run this command on your Terminal?
```
gh auth refresh -h github.com -s codespace
```

@Newtopian

**Comment by argestes** [comment]
> I've solved this issue. Can you try to run this command on your Terminal?
> 
> ```
> gh auth refresh -h github.com -s codespace
> ```
> 
> @Newtopian

This worked for me. Thanks
